'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KbbEdit.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BonusStage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BonusStage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BonusStageSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BonusStageSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Close_red_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_red_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiscordBranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiscordBranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DummyFace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DummyFace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExtraStage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExtraStage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExtraStageSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExtraStageSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FaceHole() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FaceHole", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GitHubBranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GitHubBranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ins9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ins9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Link_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Link_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LinkVertical_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinkVertical_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NoFace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoFace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenFile_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFile_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenFolder_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFolder_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OtherStage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OtherStage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OtherStageSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OtherStageSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Question_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stage1Select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stage1Select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stage2Select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stage2Select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stage3Select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stage3Select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stage4Select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stage4Select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hello!
        '''I&apos;m the help form.
        '''I will help you and explain how to import your Kbb save from your 3DS.
        '''FBI is needed, as it will let you access your save files!.
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Now, select &quot;Paste&quot;..
        '''</summary>
        Friend ReadOnly Property String10() As String
            Get
                Return ResourceManager.GetString("String10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Press A..
        '''</summary>
        Friend ReadOnly Property String11() As String
            Get
                Return ResourceManager.GetString("String11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Congratulations!
        '''Your save files are now on your SD card.
        '''Now, close FBI..
        '''</summary>
        Friend ReadOnly Property String12() As String
            Get
                Return ResourceManager.GetString("String12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à You will need to access your SD card from your computer. If you have an SD card slot on your computer, or an adapter, like a SD to USB adapter, power off your 3DS and eject your SD card from it, then put it in your PC..
        '''</summary>
        Friend ReadOnly Property String13() As String
            Get
                Return ResourceManager.GetString("String13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Else, if you can&apos;t do what was said in the previous step, use FTPDB (install it if you don&apos;t have it) or use the SD management tool in your 3DS system settings. There is a tutorial on YouTube by sthetix on how to use it..
        '''</summary>
        Friend ReadOnly Property String14() As String
            Get
                Return ResourceManager.GetString("String14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à With KbbEdit, select &quot;File&quot; then &quot;Open save&quot; and browse to your SD card using the file explorer.
        '''Then, select the folder where you pasted your save files (in my case, I called it &quot;xxxxx&quot;)..
        '''</summary>
        Friend ReadOnly Property String15() As String
            Get
                Return ResourceManager.GetString("String15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à If you get an error message, share it on our Discord server.
        '''You can join it by selecting &quot;About&quot; then &quot;Links&quot; and clicking on the invite link..
        '''</summary>
        Friend ReadOnly Property String16() As String
            Get
                Return ResourceManager.GetString("String16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à First, on your 3DS, start FBI.
        '''Go to &quot;System Save Data&quot;.
        '''</summary>
        Friend ReadOnly Property String2() As String
            Get
                Return ResourceManager.GetString("String2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Now, go down until you find &quot;0002022D&quot;.
        '''That&apos;s your Face Raiders save file.
        '''Select it..
        '''</summary>
        Friend ReadOnly Property String3() As String
            Get
                Return ResourceManager.GetString("String3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à This will show up.
        '''Select &quot;Browse Save Data&quot;.
        '''</summary>
        Friend ReadOnly Property String4() As String
            Get
                Return ResourceManager.GetString("String4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à FBI will show you a folder.
        '''Select &quot;&lt;current directory&gt;&quot;..
        '''</summary>
        Friend ReadOnly Property String5() As String
            Get
                Return ResourceManager.GetString("String5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Now, select &quot;Copy&quot;..
        '''</summary>
        Friend ReadOnly Property String6() As String
            Get
                Return ResourceManager.GetString("String6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à FBI will copy all the files in the directory.
        '''&quot;Kbb.dat&quot; is the save file.
        '''&quot;FaceF**.dat&quot; files are your saved faces.
        '''&quot;FaceP**.dat&quot; files are pictures of faces found by the UFO in your Nintendo 3DS Camera gallery..
        '''</summary>
        Friend ReadOnly Property String7() As String
            Get
                Return ResourceManager.GetString("String7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Now, go to your SD card.
        '''Then, create a folder in it by selecting &quot;&lt;current directory&gt;&quot;, then &quot;New folder&quot;..
        '''</summary>
        Friend ReadOnly Property String8() As String
            Get
                Return ResourceManager.GetString("String8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Select the folder you created.
        '''In your folder, select
        '''&quot;&lt;current directory&gt;&quot;..
        '''</summary>
        Friend ReadOnly Property String9() As String
            Get
                Return ResourceManager.GetString("String9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property titlelogo_face_1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("titlelogo_face_1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UnknownFace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnknownFace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UnknownFace2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnknownFace2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
